name: Gerar cobrinha das contribuições

on:
  schedule:
    - cron: '0 0 * * *'   # Roda todo dia à meia-noite UTC
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: BrunoBarbosaVicente
          outputs: |
            output/github-snake.svg?color_snake=#000&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            output/github-snake-dark.svg?color_snake=#fff&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Commit e push dos arquivos gerados
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
